
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'C CM DATA DATE HOUR IP KBS NUMBER S SERVER SONG START TIME\n        prog : prog_ok\n        \n        prog_ok : START C mp3_list SERVER C data_time user_list\n        \n        mp3_list : mp3 \n                    | mp3_list mp3\n        \n        mp3 : dim song_list S\n        \n        dim : NUMBER KBS C\n        \n        song : SONG NUMBER\n        \n        song_list : song\n                    | song_list CM NT0 song \n        \n        NT0 : \n        \n        data_time : TIME C HOUR DATA C DATE\n                    | DATA C DATE TIME C HOUR \n        \n        user_list : \n                    | user_list user\n        \n        user : ip C songs_list S\n        \n        ip : IP\n        \n        songs_list : SONG\n                        | songs_list CM SONG\n        '
    
_lr_action_items = {'START':([0,],[3,]),'$end':([1,2,20,24,28,40,42,43,],[0,-1,-13,-2,-14,-15,-11,-12,]),'C':([3,9,14,21,22,29,30,34,35,],[4,15,19,25,26,33,-16,38,39,]),'NUMBER':([4,5,6,10,13,16,],[8,8,-3,-4,18,-5,]),'SERVER':([5,6,10,16,],[9,-3,-4,-5,]),'SONG':([7,17,19,23,33,41,],[13,-10,-6,13,37,44,]),'KBS':([8,],[14,]),'S':([11,12,18,27,36,37,44,],[16,-8,-7,-9,40,-17,-18,]),'CM':([11,12,18,27,36,37,44,],[17,-8,-7,-9,41,-17,-18,]),'TIME':([15,32,],[21,35,]),'DATA':([15,31,],[22,34,]),'IP':([20,24,28,40,42,43,],[-13,30,-14,-15,-11,-12,]),'HOUR':([25,39,],[31,43,]),'DATE':([26,38,],[32,42,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'prog_ok':([0,],[2,]),'mp3_list':([4,],[5,]),'mp3':([4,5,],[6,10,]),'dim':([4,5,],[7,7,]),'song_list':([7,],[11,]),'song':([7,23,],[12,27,]),'data_time':([15,],[20,]),'NT0':([17,],[23,]),'user_list':([20,],[24,]),'user':([24,],[28,]),'ip':([24,],[29,]),'songs_list':([33,],[36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> prog_ok','prog',1,'p_prog','myParser.py',29),
  ('prog_ok -> START C mp3_list SERVER C data_time user_list','prog_ok',7,'p_prog_ok','myParser.py',36),
  ('mp3_list -> mp3','mp3_list',1,'p_mp3_list','myParser.py',41),
  ('mp3_list -> mp3_list mp3','mp3_list',2,'p_mp3_list','myParser.py',42),
  ('mp3 -> dim song_list S','mp3',3,'p_mp3','myParser.py',47),
  ('dim -> NUMBER KBS C','dim',3,'p_dim','myParser.py',52),
  ('song -> SONG NUMBER','song',2,'p_song','myParser.py',59),
  ('song_list -> song','song_list',1,'p_song_list','myParser.py',71),
  ('song_list -> song_list CM NT0 song','song_list',4,'p_song_list','myParser.py',72),
  ('NT0 -> <empty>','NT0',0,'p_NT0','myParser.py',77),
  ('data_time -> TIME C HOUR DATA C DATE','data_time',6,'p_data_time','myParser.py',84),
  ('data_time -> DATA C DATE TIME C HOUR','data_time',6,'p_data_time','myParser.py',85),
  ('user_list -> <empty>','user_list',0,'p_user_list','myParser.py',92),
  ('user_list -> user_list user','user_list',2,'p_user_list','myParser.py',93),
  ('user -> ip C songs_list S','user',4,'p_user','myParser.py',98),
  ('ip -> IP','ip',1,'p_ip','myParser.py',105),
  ('songs_list -> SONG','songs_list',1,'p_songs_list','myParser.py',112),
  ('songs_list -> songs_list CM SONG','songs_list',3,'p_songs_list','myParser.py',113),
]
