
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'C CM EURO ID INT S SEP\n        prog : products SEP receipts\n        \n        products : products product\n                    | product\n        \n        product : ID EURO S\n        \n        receipts : receipts receipt\n                    | \n        \n        receipt : ID C purchasedProducts S\n        \n        purchasedProducts : purchasedProducts CM purchasedProduct\n                                | purchasedProduct\n        \n        purchasedProduct : INT ID\n        '
    
_lr_action_items = {'ID':([0,2,3,5,6,8,9,10,15,16,],[4,4,-3,-6,-2,11,-4,-5,18,-7,]),'$end':([1,5,8,10,16,],[0,-6,-1,-5,-7,]),'SEP':([2,3,6,9,],[5,-3,-2,-4,]),'EURO':([4,],[7,]),'S':([7,13,14,18,19,],[9,16,-9,-10,-8,]),'C':([11,],[12,]),'INT':([12,17,],[15,15,]),'CM':([13,14,18,19,],[17,-9,-10,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'products':([0,],[2,]),'product':([0,2,],[3,6,]),'receipts':([5,],[8,]),'receipt':([8,],[10,]),'purchasedProducts':([12,],[13,]),'purchasedProduct':([12,17,],[14,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> products SEP receipts','prog',3,'p_prog','myParser.py',29),
  ('products -> products product','products',2,'p_products','myParser.py',35),
  ('products -> product','products',1,'p_products','myParser.py',36),
  ('product -> ID EURO S','product',3,'p_product','myParser.py',41),
  ('receipts -> receipts receipt','receipts',2,'p_receipts','myParser.py',50),
  ('receipts -> <empty>','receipts',0,'p_receipts','myParser.py',51),
  ('receipt -> ID C purchasedProducts S','receipt',4,'p_receipt','myParser.py',56),
  ('purchasedProducts -> purchasedProducts CM purchasedProduct','purchasedProducts',3,'p_purchasedProducts','myParser.py',63),
  ('purchasedProducts -> purchasedProduct','purchasedProducts',1,'p_purchasedProducts','myParser.py',64),
  ('purchasedProduct -> INT ID','purchasedProduct',2,'p_purchasedProduct','myParser.py',77),
]
