
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CM EMPTY ID NUM S SC SO TIMES TYPE\n        Decll :  Decll Decl S\n                    | empty\n        \n        Decll : Decll error S\n        \n        Decl : T Vlist\n        \n        T : TYPE\n        \n        Vlist : V\n                | Vlist CM NT0 V\n        \n        NT0 : empty\n        \n        V : Ptr ID Ary\n        \n        Ptr : empty\n                | Ptr TIMES\n        \n        Ary : empty\n                | Ary SO NUM SC\n        \n        empty :\n        '
    
_lr_action_items = {'error':([0,1,2,7,8,],[-14,4,-2,-1,-3,]),'TYPE':([0,1,2,7,8,],[-14,6,-2,-1,-3,]),'$end':([0,1,2,7,8,],[-14,0,-2,-1,-3,]),'S':([3,4,9,10,14,18,19,20,23,],[7,8,-4,-6,-14,-9,-12,-7,-13,]),'ID':([5,6,11,12,13,15,16,17,],[-14,-5,14,-10,-14,-11,-14,-8,]),'TIMES':([5,6,11,12,13,15,16,17,],[-14,-5,15,-10,-14,-11,-14,-8,]),'CM':([9,10,14,18,19,20,23,],[13,-6,-14,-9,-12,-7,-13,]),'SO':([14,18,19,23,],[-14,21,-12,-13,]),'NUM':([21,],[22,]),'SC':([22,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Decll':([0,],[1,]),'empty':([0,5,13,14,16,],[2,12,17,19,12,]),'Decl':([1,],[3,]),'T':([1,],[5,]),'Vlist':([5,],[9,]),'V':([5,16,],[10,20,]),'Ptr':([5,16,],[11,11,]),'NT0':([13,],[16,]),'Ary':([14,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Decll","S'",1,None,None,None),
  ('Decll -> Decll Decl S','Decll',3,'p_Decll','myParser.py',57),
  ('Decll -> empty','Decll',1,'p_Decll','myParser.py',58),
  ('Decll -> Decll error S','Decll',3,'p_Decll_error','myParser.py',63),
  ('Decl -> T Vlist','Decl',2,'p_Decl','myParser.py',70),
  ('T -> TYPE','T',1,'p_T','myParser.py',76),
  ('Vlist -> V','Vlist',1,'p_Vlist','myParser.py',84),
  ('Vlist -> Vlist CM NT0 V','Vlist',4,'p_Vlist','myParser.py',85),
  ('NT0 -> empty','NT0',1,'p_NT0','myParser.py',92),
  ('V -> Ptr ID Ary','V',3,'p_V','myParser.py',99),
  ('Ptr -> empty','Ptr',1,'p_Ptr','myParser.py',109),
  ('Ptr -> Ptr TIMES','Ptr',2,'p_Ptr','myParser.py',110),
  ('Ary -> empty','Ary',1,'p_Ary','myParser.py',123),
  ('Ary -> Ary SO NUM SC','Ary',4,'p_Ary','myParser.py',124),
  ('empty -> <empty>','empty',0,'p_empty','myParser.py',143),
]
