
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'C CM DATA DATE HOUR IP KBS NUMBER S SERVER SONG START TIME\n        prog : prog_ok\n        \n        prog_ok : START C mp3_list SERVER C data_time user_list\n        \n        mp3_list : mp3 \n                    | mp3_list mp3\n        \n        mp3 : NUMBER KBS C song_list S\n        \n        song_list : SONG NUMBER \n                        | song_list CM SONG NUMBER \n        \n        data_time : TIME C HOUR DATA C DATE\n                    | DATA C DATE TIME C HOUR \n        \n        user_list : \n                    | user_list user\n        \n        user : ip C songs_list S\n        \n        ip : IP\n        \n        songs_list : SONG\n                        | songs_list CM SONG\n        '
    
_lr_action_items = {'START':([0,],[3,]),'$end':([1,2,13,18,24,38,40,41,],[0,-1,-10,-2,-11,-12,-8,-9,]),'C':([3,8,10,14,15,25,26,31,32,],[4,11,12,19,20,30,-13,36,37,]),'NUMBER':([4,5,6,9,17,21,29,],[7,7,-3,-4,23,-5,33,]),'SERVER':([5,6,9,21,],[8,-3,-4,-5,]),'KBS':([7,],[10,]),'TIME':([11,28,],[14,32,]),'DATA':([11,27,],[15,31,]),'SONG':([12,22,30,39,],[17,29,35,42,]),'IP':([13,18,24,38,40,41,],[-10,26,-11,-12,-8,-9,]),'S':([16,23,33,34,35,42,],[21,-6,-7,38,-14,-15,]),'CM':([16,23,33,34,35,42,],[22,-6,-7,39,-14,-15,]),'HOUR':([19,37,],[27,41,]),'DATE':([20,36,],[28,40,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'prog_ok':([0,],[2,]),'mp3_list':([4,],[5,]),'mp3':([4,5,],[6,9,]),'data_time':([11,],[13,]),'song_list':([12,],[16,]),'user_list':([13,],[18,]),'user':([18,],[24,]),'ip':([18,],[25,]),'songs_list':([30,],[34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> prog_ok','prog',1,'p_prog','myParser.py',27),
  ('prog_ok -> START C mp3_list SERVER C data_time user_list','prog_ok',7,'p_prog_ok','myParser.py',34),
  ('mp3_list -> mp3','mp3_list',1,'p_mp3_list','myParser.py',39),
  ('mp3_list -> mp3_list mp3','mp3_list',2,'p_mp3_list','myParser.py',40),
  ('mp3 -> NUMBER KBS C song_list S','mp3',5,'p_mp3','myParser.py',45),
  ('song_list -> SONG NUMBER','song_list',2,'p_song_list','myParser.py',50),
  ('song_list -> song_list CM SONG NUMBER','song_list',4,'p_song_list','myParser.py',51),
  ('data_time -> TIME C HOUR DATA C DATE','data_time',6,'p_data_time','myParser.py',72),
  ('data_time -> DATA C DATE TIME C HOUR','data_time',6,'p_data_time','myParser.py',73),
  ('user_list -> <empty>','user_list',0,'p_user_list','myParser.py',80),
  ('user_list -> user_list user','user_list',2,'p_user_list','myParser.py',81),
  ('user -> ip C songs_list S','user',4,'p_user','myParser.py',86),
  ('ip -> IP','ip',1,'p_ip','myParser.py',93),
  ('songs_list -> SONG','songs_list',1,'p_songs_list','myParser.py',100),
  ('songs_list -> songs_list CM SONG','songs_list',3,'p_songs_list','myParser.py',101),
]
