
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CM ID S TYPE\n        goal : list_decl\n        \n        list_decl : \n                    | list_decl decl \n        \n        decl : TYPE lid S\n        \n        lid : ID CM r_copy lid\n                | ID \n        \n        r_copy : \n        '
    
_lr_action_items = {'TYPE':([0,2,3,7,],[-2,4,-3,-4,]),'$end':([0,1,2,3,7,],[-2,0,-1,-3,-4,]),'ID':([4,8,9,],[6,-7,6,]),'S':([5,6,10,],[7,-6,-5,]),'CM':([6,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'goal':([0,],[1,]),'list_decl':([0,],[2,]),'decl':([2,],[3,]),'lid':([4,9,],[5,10,]),'r_copy':([8,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> goal","S'",1,None,None,None),
  ('goal -> list_decl','goal',1,'p_goal','myParser.py',28),
  ('list_decl -> <empty>','list_decl',0,'p_list_decl','myParser.py',35),
  ('list_decl -> list_decl decl','list_decl',2,'p_list_decl','myParser.py',36),
  ('decl -> TYPE lid S','decl',3,'p_decl','myParser.py',41),
  ('lid -> ID CM r_copy lid','lid',4,'p_lid','myParser.py',48),
  ('lid -> ID','lid',1,'p_lid','myParser.py',49),
  ('r_copy -> <empty>','r_copy',0,'p_r_copy','myParser.py',63),
]
